services:

  proxy:
    image: haproxy:lts-alpine3.23
    ports:
      - 8088:8088
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - my-network
  rest:
    build:
      context: .
      dockerfile: ./services/core/cmd/Dockerfile
    # ports:
    #   - 8080:8888
    expose:
      - 8888
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - my-network
    volumes:
      - ./shared/config:/app/config

  parserserver:
    build:
      context: .
      dockerfile: ./services/parser/cmd/Dockerfile
    expose:
      - 50043
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - my-network
    volumes:
      - ./shared/config:/app/config

  narrator:
    build:
      context: .
      dockerfile: ./services/narrator/cmd/Dockerfile
    depends_on:
      - kafka
    networks:
      - my-network
    volumes:
      - ./shared/config:/app/config

  postgres:
    image: postgres:18.0-alpine3.22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=veryStrongPassword
      - POSTGRES_DB=SumTel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - my-network
    healthcheck:
      test: "pg_isready -h postgres"
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - my-network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka
    networks:
      - my-network

  migrator:
    build:
      context: .
      dockerfile: ./services/migrator/cmd/Dockerfile
    volumes:
      - ./shared/config:/services/migrator/config
      - ./services/core/migrations:/services/migrator/core-migrations
      - ./services/parser/migrations:/services/migrator/parser-migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network
  
  prometheus:
    image: prom/prometheus:v3.8.0-rc.1
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - my-network
  grafana:
    image: grafana/grafana:12.1
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./metrics/grafana/grafana.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_storage:/var/lib/grafana
    networks:
      - my-network

volumes:
  db_data:
  kafka_data:
  prometheus_data:
  grafana_storage:
networks:
  my-network:
    driver: bridge
