global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rest"
    static_configs:
      - targets: ["rest:9090"]
  
  - job_name: "narrator"
    static_configs:
      - targets: ["narrator:9090"]
