appConfig:
  Env: "local"
grpcServerConfig:
  GPRPCPort: 50043

postgresConfig:
  DbHost: "postgres"
  DbPort: 5432
  DbUser: "parseruser"
  DbName: "parserdb"
  DbPassword: "parserpassword"
  DbSslMode: "disable"

rawMessageProducerConfig:
  Topic: "raw-messages"
  Broker: "kafka:9092"
  BatchSize: 3
